spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:dev/,pro/,test/
  application:
    name: config-server
  profiles:
    active: native
  zipkin:
    base-url: http://localhost:9411

server:
  port: 7006

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
