server:
  port: 8181
spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      routes:
          id: gateway-service
          uri: https://blog.csdn.net
          predicates:
            - Path=/meteor_93
